### ISSUE TITLE
asm.js and wasm32 don't work anymore

### ISSUE THREAD

**Issue by CryZe** [japaric/cross#110]
I'm not entirely sure what happened, but cross can't compile my code anymore, even though nothing changed in either my code, the rust compiler or cross. I assume Travis themselves broke something.

https://travis-ci.org/CryZe/livesplit-core/jobs/245407142#L596

```
  = note: WARNING:root:(Emscripten: unknown: [Errno 13] Permission denied, clearing cache)
          CRITICAL:root:Could not verify LLVM version: [Errno 13] Permission denied
          CRITICAL:root:fastcomp in use, but LLVM has not been built with the JavaScript backend as a target, llc reports:
          ===========================================================================
          (no targets could be identified: [Errno 13] Permission denied)
          ===========================================================================
          CRITICAL:root:you can fall back to the older (pre-fastcomp) compiler core, although that is not recommended, see http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
          INFO:root:(Emscripten: Running sanity checks)
          CRITICAL:root:failing sanity checks due to previous fastcomp failure
```

**Comment by CryZe** [comment]
Looks like they updated the docker version (and tons of other versions).

Before:

```
[34m[1mdocker version[0m
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

After:
```
[34m[1mdocker version[0m
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by jan-hudec** [comment]
Confirming. See https://travis-ci.org/rust-locale/locale_config/jobs/273389272

I will shortly retry with nightly on Travis and locally and report the results.

@CryZe, the message says emcc doesn't like something about LLVM. Since both are installed by cross and not taken from the Travis image, it seems more like mismatch between something in the cross docker image and newer rust compiler.

**Comment by CryZe** [comment]
In the meantime you can downgrade your Travis environment btw.

https://github.com/CryZe/LiveSplitOne/blob/master/.travis.yml#L34

This doesn't really fix the problem, but it at least fixes it until they shut down the old environments.

**Comment by jan-hudec** [comment]
Locally everything appears to work fine¹! I have up-to-date Debian Buster and up-to-date `rustc 1.20.0 (f3d6973f4 2017-08-27)` and `rustc 1.22.0-nightly (d93036a04 2017-09-07)`. Both work with cross 0.1.11 and both `asmjs-unknown-emscripten` and `wasm32-unknown-emscripten`.

Ok, @CryZe, that's interesting. Because *ancient* version of *something* works fine, *new* version works *also fine*, but *old* version does not. Now the question is *what* is that *something*. The build shouldn't actually be using much from the Travis base system.

**Comment by jan-hudec** [comment]
Hm, downgrading the Travis image does indeed make the error go away (https://travis-ci.org/rust-locale/locale_config/builds/273441697). By *why*‽

The image does contain LLVM, but:

 * The package manifests indicate that it was not updated and
 * emscripten should be using its own copy anyway.

Unfortunately the error is pretty much devoid of useful information. We really need to know permission to *what* is denied.

However, it seems the error is coming from check of *clang* version, and the package manifest diff for the update does not even mention that, and llvm it only mentions in context as unchanged.

**Comment by jan-hudec** [comment]
@CryZe, also, Travis reports they've upgraded again yesterday (2017-09-07), so apparently that image has the same problem as the previous.

**Comment by jan-hudec** [comment]
> Looks like they updated their worker images, including a massive change in docker version.
> ```
> Version:      1.12.3
> Version:      17.03.1-ce
> ```

Hm, Debian Buster has
```
Version:      1.13.1
```

Ok. So where did they get that version. Oh, apparently the [upstream repository](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/). Ok, so let's install that…

First, the “current stable” version:
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:58:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
and it ***works!***

So the same as Travis:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
and it ***also works!***

Ok, so it does *not* seem to be caused by difference in docker. But difference in what then? The docker image should be self-contained…

@malbarbo, you added the support initially, do you have any idea what might be causing that error?

**Comment by malbarbo** [comment]
It seems that emscripten is failing to execute some clang tool. In #125 I try to fix the problem adding execution permission for everyone.

**Comment by jan-hudec** [comment]
Does *not* appear to be fixed: https://travis-ci.org/rust-locale/locale_config/jobs/278730580

**Comment by jan-hudec** [comment]
Confirming, works now.
