### ISSUE TITLE
build.rs build script fails

### ISSUE THREAD

**Issue by droundy** [japaric/cross#116]
When building with cross (but not with cargo) I get weird build errors when running my `build.rs`:

https://travis-ci.org/droundy/fac/builds/254944182

Sorry to be terse.  I'm still debugging my travis configuration, but it's clear that `cross` was breaking it.

**Comment by lawliet89** [comment]
The clue is in [these lines](https://travis-ci.org/droundy/fac/jobs/254944185#L591-L593): your `build.rs` tried to write a `version.rs` file. But `cross` mounts the path as read-only as listed in the README under [caveats/gotchas](https://github.com/japaric/cross/tree/d48a6dfd7ef96b17fdd6b253721b4c6a2a016eb6#caveats--gotchas).

**Comment by droundy** [comment]
Is there a way to generate source code that only writes to $OUT_DIR?

**Comment by japaric** [comment]
@droundy check [rustup], it does something similar to what you are doing to get the commit hash but it writes a temporary file to [$OUT_DIR], instead of to the `src` directory. Here's how it reads back that file [into source code].

[rustup]: https://github.com/rust-lang-nursery/rustup.rs
[$OUT_DIR]: https://github.com/rust-lang-nursery/rustup.rs/blob/b33d20a91dc189d99f3e21e3a4762d07c57801da/build.rs#L19
[into source code]: https://github.com/rust-lang-nursery/rustup.rs/blob/b33d20a91dc189d99f3e21e3a4762d07c57801da/src/rustup-cli/common.rs#L369

**Comment by jamesmunns** [comment]
@droundy were you able to get this working? Would this be okay to close?

**Comment by droundy** [comment]
Yes, I did get this working.
