### ISSUE TITLE
`core` lib on thumb* targets

### ISSUE THREAD

**Issue by dhardy** [japaric/cross#152]
First, I'm not sure if this is *supposed* to work or not..

I'm using Cross with a subset of the Trust scripts to build/test the `rand` lib on multiple platforms, and enabled `thumbv7em` to test `no_std` builds on a platform which doesn't actually have `std`.

[What I get](https://travis-ci.org/dhardy/rand/jobs/301379462):

> error[E0463]: can't find crate for `core`
>   |
>   = note: the `thumbv7em-none-eabi` target may not be installed

This target *should* have the `core` crate available, right?

[Relevant PR](https://github.com/dhardy/rand/pull/46)

**Comment by japaric** [comment]
> This target should have the core crate available, right?

There are *no* binary releases of `core` for the thumb targets. Cross will use Xargo to build `core` on the fly for these targets but that requires a nightly toolchain (because `core` heavily depends on unstable features). It doesn't work for you because you are using a stable toolchain; try the nightly toolchain.

**Comment by malbarbo** [comment]
We should add this information to the README. I opened an issue https://github.com/japaric/cross/issues/154

**Comment by dhardy** [comment]
Thanks. I see that it now compiles `core` but still has a dependency on `std` for some reason. Anyway, my problem, not yours.
