### ISSUE TITLE
{i*,x86_64}-pc-windows-gnu could be supported

### ISSUE THREAD

**Issue by nagisa** [japaric/cross#65]
Supporting cross compilation from unix to *-pc-windows-gnu is easy with the mingw toolchain, which happens to include `.lib`s for the system libraries.

**Comment by japaric** [comment]
Certainly. IIRC, cross compiling to x86_64 mingw works out of the box with Ubuntu's packaged toolchain but i686 mingw because that toolchain has been configured with a different threading model or something. We'l have to get or build a different toolchain for that target.

It may even be possible to hook binfmt with wine to get `cargo run` working. (Or perhaps that already works with having to do anything? I don't remember)
