### ISSUE TITLE
Update openssl to 1.0.2k

### ISSUE THREAD

**Issue by malbarbo** [japaric/cross#79]

**Comment by japaric** [comment]
If you want to tackle this, you'd have to just change all the Dockerfiles to install 1.0.2k instead of 1.0.2j. It would probably be a good idea to move the openssl version into the openssl.sh script to avoid repeating the version everywhere; I don't see a reason why one target would want to use an older / different version than the others.

**Comment by malbarbo** [comment]
I will give it a try after https://github.com/japaric/cross/pull/81 got merged.
